# Generated by Django 4.2.6 on 2024-01-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_delete_car1'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
